##
# Azure Pipeline CI build and PR build

# Copyright (c) 2019, Microsoft Corporation
# SPDX-License-Identifier: BSD-2-Clause-Patent
##
resources:
  repositories:
    - repository: pytool_extensions
      type: github
      name: matthewfcarlson/edk2-pytool-extensions
      ref: refs/heads/feature/code-coverage
      endpoint: matthewfcarlson

# trigger on master for CI and all PRs for master
trigger: 
- master

pr: 
- master

jobs:

- template: azure-pipelines/templates/build-test-job.yml@pytool_extensions
  parameters:
    vm_image: 'ubuntu-latest'
    root_package_folder: "edk2toolbase"
    name: 'ubuntu'
